import Link from "next/link";
import LegalPageLayout from "../components/landing/LegalPageLayout";

export default function TermsPage() {
  return (
    <LegalPageLayout title="Terms">
      <p>Welcome to Zelos.</p>
      <p>
        By using Zelos, you agree to use the service responsibly and in accordance with applicable
        laws.
      </p>

      <h2>What Zelos is</h2>
      <p>
        Zelos is a productivity and self-reflection tool designed to help users understand
        blockers, reduce overwhelm, and take meaningful action.
      </p>

      <h2>What Zelos is not</h2>
      <ul>
        <li>Therapy</li>
        <li>Medical treatment</li>
        <li>Mental health care</li>
        <li>Crisis intervention</li>
        <li>Professional psychological advice</li>
      </ul>

      <h2>User Responsibility</h2>
      <p>
        You are responsible for the information you provide and the decisions you make based on
        information generated by Zelos.
      </p>

      <h2>Availability</h2>
      <p>We may modify, improve, suspend, or discontinue features at any time.</p>

      <h2>Limitation of Liability</h2>
      <p>
        Zelos is provided &ldquo;as is&rdquo; without guarantees of accuracy, completeness, or
        suitability for any particular purpose.
      </p>

      <h2>Contact</h2>
      <ul>
        <li>
          Questions regarding these terms?{" "}
          <Link href="mailto:contact@zelos.app">contact@zelos.app</Link>
        </li>
      </ul>
    </LegalPageLayout>
  );
}
