import type { InsightsPageData, PatternOccurrence } from "./types";

export const mockInsightsPage: InsightsPageData = {
  hasData: true,
  summary: {
    activeGoals: 2,
    patternsDetected: 7,
    playbookRulesLearned: 8,
    experimentsCompleted: 3,
  },
  behavioralProfile: [
    { label: "Self Awareness", value: 82 },
    { label: "Action Taking", value: 58 },
    { label: "Consistency", value: 64 },
    { label: "Decision Clarity", value: 46 },
    { label: "Follow Through", value: 52 },
    { label: "Adaptability", value: 71 },
  ],
  patterns: [
    {
      id: "pat-research-spiral",
      name: "Research Spiral",
      description:
        "You often gather more information before committing to an experiment.",
      confidence: 72,
      observedCount: 8,
      lastObservedAt: "Yesterday",
      goals: [
        { goalId: "goal-1", goalTitle: "Build Zelos MVP", count: 6 },
        { goalId: "goal-2", goalTitle: "Job Switch", count: 2 },
      ],
      trend: "increasing",
    },
    {
      id: "pat-decision-loop",
      name: "Decision Loop",
      description: "You compare multiple options without choosing one next step.",
      confidence: 61,
      observedCount: 5,
      lastObservedAt: "2 days ago",
      goals: [{ goalId: "goal-1", goalTitle: "Build Zelos MVP", count: 5 }],
      trend: "stable",
    },
    {
      id: "pat-topic-drift",
      name: "Topic Drift",
      description: "You shift topics when execution starts to feel uncomfortable.",
      confidence: 54,
      observedCount: 3,
      lastObservedAt: "4 days ago",
      goals: [{ goalId: "goal-1", goalTitle: "Build Zelos MVP", count: 3 }],
      trend: "decreasing",
    },
    {
      id: "pat-action-gap",
      name: "Action Gap",
      description: "You know the next step but delay taking it.",
      confidence: 48,
      observedCount: 4,
      lastObservedAt: "3 days ago",
      goals: [
        { goalId: "goal-2", goalTitle: "Job Switch", count: 2 },
        { goalId: "goal-1", goalTitle: "Build Zelos MVP", count: 2 },
      ],
      trend: "stable",
    },
    {
      id: "pat-perfectionism",
      name: "Perfectionism Loop",
      description: "You wait for the version that feels fully ready before shipping.",
      confidence: 45,
      observedCount: 2,
      lastObservedAt: "1 week ago",
      goals: [{ goalId: "goal-1", goalTitle: "Build Zelos MVP", count: 2 }],
      trend: "decreasing",
    },
  ],
  occurrences: [
    {
      id: "occ-1",
      patternId: "pat-research-spiral",
      goalId: "goal-1",
      goalTitle: "Build Zelos MVP",
      conversationId: "conv-1",
      messageId: "msg_123",
      confidence: 82,
      evidenceText:
        "You compared multiple frontend layouts without committing to one.",
      messagePreview:
        "Should we do 2-panel or 3-panel layout? I don't want it to feel like ChatGPT…",
      createdAt: "2026-06-20",
    },
    {
      id: "occ-2",
      patternId: "pat-research-spiral",
      goalId: "goal-1",
      goalTitle: "Build Zelos MVP",
      conversationId: "conv-1",
      messageId: "msg_98",
      confidence: 74,
      evidenceText: "More competitor examples were added before a decision.",
      messagePreview: "I keep finding apps that do something similar. Maybe I need more research.",
      createdAt: "2026-06-18",
    },
    {
      id: "occ-3",
      patternId: "pat-research-spiral",
      goalId: "goal-2",
      goalTitle: "Job Switch",
      conversationId: "conv-2",
      messageId: "msg_44",
      confidence: 68,
      evidenceText: "Resume research expanded without sending applications.",
      messagePreview: "I found three more resume templates but haven't applied anywhere.",
      createdAt: "2026-06-15",
    },
    {
      id: "occ-4",
      patternId: "pat-decision-loop",
      goalId: "goal-1",
      goalTitle: "Build Zelos MVP",
      conversationId: "conv-1",
      messageId: "msg_110",
      confidence: 65,
      evidenceText: "Layout options were weighed again without picking one.",
      messagePreview: "What if we tried a sidebar-only approach instead?",
      createdAt: "2026-06-19",
    },
  ],
  playbook: {
    worksWell: [
      "Breaking big decisions into one next step",
      "Small deadlines that create momentum",
      "Talking through uncertainty before acting",
      "Committing before feeling fully ready",
      "Focusing on actions instead of outcomes",
    ],
    doesNotWork: [
      "Researching for weeks without testing",
      "Comparing every option before choosing",
      "Waiting until confidence appears",
      "Restarting plans instead of continuing",
      "Avoiding uncomfortable conversations",
    ],
  },
  timeline: [
    {
      id: "tl-i1",
      type: "goal_created",
      title: "Goal started: Build Zelos MVP",
      goalTitle: "Build Zelos MVP",
      createdAt: new Date(Date.now() - 14 * 86400000),
    },
    {
      id: "tl-i2",
      type: "pattern_detected",
      title: "Research Spiral detected",
      goalTitle: "Build Zelos MVP",
      createdAt: new Date(Date.now() - 10 * 86400000),
    },
    {
      id: "tl-i3",
      type: "decision_made",
      title: "Decision made: 3-panel workspace",
      goalTitle: "Build Zelos MVP",
      createdAt: new Date(Date.now() - 5 * 86400000),
    },
    {
      id: "tl-i4",
      type: "experiment_started",
      title: "Experiment started: ship landing page first",
      goalTitle: "Build Zelos MVP",
      createdAt: new Date(Date.now() - 4 * 86400000),
    },
    {
      id: "tl-i5",
      type: "playbook_updated",
      title: "Playbook updated: small deadlines help",
      goalTitle: "Build Zelos MVP",
      createdAt: new Date(Date.now() - 2 * 86400000),
    },
    {
      id: "tl-i6",
      type: "action_completed",
      title: "First user feedback collected",
      goalTitle: "Build Zelos MVP",
      createdAt: new Date(Date.now() - 1 * 86400000),
    },
  ],
  activeExperiments: [
    {
      id: "exp-1",
      title: "Pick one idea and test it for 48 hours",
      goalTitle: "Build Zelos MVP",
      status: "active",
      date: new Date(Date.now() - 2 * 86400000),
    },
    {
      id: "exp-2",
      title: "Send two applications before editing resume again",
      goalTitle: "Job Switch",
      status: "active",
      date: new Date(Date.now() - 1 * 86400000),
    },
  ],
  completedExperiments: [
    {
      id: "exp-3",
      title: "Finalize one frontend layout",
      goalTitle: "Build Zelos MVP",
      status: "completed",
      date: new Date(Date.now() - 5 * 86400000),
    },
    {
      id: "exp-4",
      title: "Write one imperfect landing page draft",
      goalTitle: "Build Zelos MVP",
      status: "completed",
      date: new Date(Date.now() - 7 * 86400000),
    },
  ],
};

export function getOccurrencesForPattern(
  patternId: string,
  occurrences: PatternOccurrence[] = mockInsightsPage.occurrences
): PatternOccurrence[] {
  return occurrences.filter((o) => o.patternId === patternId);
}
